server:
  port: 8888
  address: 0.0.0.0

###################
## Apache Solr
###################
data:
  solr:
    host: http://localhost:8984/solr


datasource:
  url: jdbc:mysql://localhost:3306/glue?characterEncoding=UTF-8&serverTimezone=UTC&
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root